//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.micajah.www.BackOfficePortfolio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BackOfficePortfolio.Iportfolio")]
    public interface Iportfolio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iportfolio/GetPortfolioDetail", ReplyAction="http://tempuri.org/Iportfolio/GetPortfolioDetailResponse")]
        System.Data.DataSet GetPortfolioDetail(System.Guid PortfolioGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iportfolio/GetPortfolioList", ReplyAction="http://tempuri.org/Iportfolio/GetPortfolioListResponse")]
        System.Data.DataSet GetPortfolioList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iportfolio/GetPortfolioScreenshots", ReplyAction="http://tempuri.org/Iportfolio/GetPortfolioScreenshotsResponse")]
        System.Data.DataTable GetPortfolioScreenshots(System.Guid PortfolioGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IportfolioChannel : web.micajah.www.BackOfficePortfolio.Iportfolio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IportfolioClient : System.ServiceModel.ClientBase<web.micajah.www.BackOfficePortfolio.Iportfolio>, web.micajah.www.BackOfficePortfolio.Iportfolio {
        
        public IportfolioClient() {
        }
        
        public IportfolioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IportfolioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IportfolioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IportfolioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetPortfolioDetail(System.Guid PortfolioGuid) {
            return base.Channel.GetPortfolioDetail(PortfolioGuid);
        }
        
        public System.Data.DataSet GetPortfolioList() {
            return base.Channel.GetPortfolioList();
        }
        
        public System.Data.DataTable GetPortfolioScreenshots(System.Guid PortfolioGuid) {
            return base.Channel.GetPortfolioScreenshots(PortfolioGuid);
        }
    }
}
