<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    CodeBehind="AccountEdit.aspx.cs" Inherits="web.micajah.backoffice.Pages.AccountEdit"
    Title="Account Edit" %>

<%@ MasterType VirtualPath="~/MasterPage.master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageBody" runat="server">
    <mits:MagicForm ObjectName="Account" ID="Account_Edit" runat="server" AutoGenerateInsertButton="True"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DefaultMode="Edit"
        ShowCloseButtonSeparate="False" DataKeyNames="AccountGuid" AutoGenerateRows="false"
        RepeatColumns="1" DataSourceID="LinqDataSource_Edit" ColorScheme="Gray">
        <Fields>
            <mits:TextBoxField ValidationErrorMessage="Please, enter account name" DataField="AccountName"
                HeaderText="Account Name" ReadOnly="False" MaxLength="49" Required="True" Columns="30" />
            <mits:TextBoxField DataField="URL" HeaderText="Account URL" ReadOnly="False" MaxLength="249"
                Columns="80" ValidationType="RegularExpression" ValidationExpression="^\s*(http://|https://)(\w|\W){0,240}\s*$"
                TextType="TextWithLiterals" ErrorMessage="Only well-formed URL allowed" />
            <mits:CheckBoxField DataField="Partner" HeaderText="Partner" ReadOnly="False" />
            <mits:TemplateField HeaderText="Logo">
                <ItemTemplate>
                    <mfs:ImageUpload ID="iuLogo" runat="server" LocalObjectType="Account" EnablePopupWindow="false" />
                    <asp:Panel ID="InsertPanel" runat="server" Visible="false">
                        You can upload logo after saving current account</asp:Panel>
                </ItemTemplate>
            </mits:TemplateField>
        </Fields>
    </mits:MagicForm>
    <asp:LinqDataSource ID="LinqDataSource_Edit" runat="server" ContextTypeName="web.micajah.backoffice.AppCode.BackOfficeDataContext"
        TableName="BackOffice_Accounts" EnableDelete="true" EnableInsert="true" EnableUpdate="true">
    </asp:LinqDataSource>
</asp:Content>
