<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PortfolioEdit.aspx.cs"
    Inherits="web.micajah.backoffice.Pages.PortfolioEdit" MasterPageFile="~/MasterPage.master" %>

<asp:Content runat="server" ContentPlaceHolderID="PageBody" ID="Content1">
    <table>
        <tr>
            <td>
                <mits:MagicForm ObjectName="Portfolio" ID="Portfolio_Edit" runat="server" AutoGenerateInsertButton="True"
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DefaultMode="Insert"
                    ShowCloseButtonSeparate="False" DataKeyNames="PortfolioGuid" AutoGenerateRows="false"
                    RepeatColumns="1" DataSourceID="LinqDataSource_Edit" ColorScheme="Gray">
                    <Fields>
                        <mits:ComboBoxField DataField="AccountGuid" DataValueField="AccountGuid" DataTextField="AccountName"
                            AllowCustomText="false" HeaderText="Account" DataSourceId="LinqDataSource_AccountList"
                            ControlStyle-Width="300px" />
                        <mits:TextBoxField DataField="PortfolioName" HeaderText="Name" ReadOnly="False" Required="True"
                            ValidationErrorMessage="Please, enter portfolio name" Columns="58" MaxLength="74"
                            TextType="Text" />
                        <mits:TextBoxField DataField="Overview" HeaderText="Overview" ReadOnly="False" TextMode="MultiLine"
                            Rows="6" Columns="60" TextType="TextWithPromptAndLiterals" />
                        <mits:TextBoxField DataField="Technologies" HeaderText="Technologies" ReadOnly="False"
                            Required="false" TextMode="MultiLine" Rows="6" Columns="60" TextType="TextWithPromptAndLiterals" />
                        <mits:TextBoxField DataField="Text" HeaderText="Text" ReadOnly="False" Required="false"
                            TextMode="MultiLine" Rows="10" Columns="60" TextType="TextWithPromptAndLiterals" />
                        <mits:TextBoxField DataField="Partners" HeaderText="Partners" ReadOnly="False" Required="false"
                            TextMode="MultiLine" Rows="6" Columns="60" ValidationType="RegularExpression"
                            ValidationExpression="^\s*(\w|\W|\s){0,249}\s*$" TextType="TextWithPromptAndLiterals" />
                        <mits:CheckBoxField DataField="Active" HeaderText="Active" ReadOnly="False" Required="false" />
                        <mits:TextBoxField DataField="PortfolioOrder" HeaderText="Order (int value)" ReadOnly="False"
                            Required="false" ValidationType="RegularExpression" ValidationExpression="^\s*(-){0,1}(\d){0,5}\s*$"
                            TextType="Text" ErrorMessage="Only int values allowed" DefaultText="0" />
                        <mits:TemplateField HeaderText="Special Image">
                            <ItemTemplate>
                                <mfs:ImageUpload ID="iuSpecial" runat="server" LocalObjectType="Special" EnablePopupWindow="false" />
                                <asp:Panel ID="InsertPanel" runat="server" Visible="false">
                                    You can upload logo after saving current account</asp:Panel>
                            </ItemTemplate>
                        </mits:TemplateField>
                        <mits:TemplateField HeaderText="Files">
                            <ItemTemplate>
                                <asp:Panel ID="InsertPanelFiles" runat="server" Visible="false">
                                    You can upload files after saving current account</asp:Panel>
                                <mfs:SimpleUpload ID="suScreenShots" runat="server" LocalObjectType="Portfolio" UploadControlsUniqueId="ctl00$PageBody$Portfolio_Edit$btnUpdateClose"
                                    MaxFilesCount="20" OnInit="suScreenShots_Init" />
                                <div style="padding-top: 7px;">
                                    <mfs:FileList ID="flScreenShots" runat="server" LocalObjectType="Portfolio" EnableDeleting="false"
                                        RenderingMode="ThumbnailsList" ShowViewAllAtOnceLink="false" />
                                </div>
                            </ItemTemplate>
                        </mits:TemplateField>
                    </Fields>
                </mits:MagicForm>
            </td>
        </tr>
    </table>
    <asp:LinqDataSource ID="LinqDataSource_Edit" runat="server" ContextTypeName="web.micajah.backoffice.AppCode.BackOfficeDataContext"
        TableName="BackOffice_Portfolios" EnableDelete="true" EnableInsert="true" EnableUpdate="true">
    </asp:LinqDataSource>
    <asp:LinqDataSource ID="LinqDataSource_AccountList" runat="server" ContextTypeName="web.micajah.backoffice.AppCode.BackOfficeDataContext"
        TableName="BackOffice_Accounts" Select="new(AccountGuid, AccountName)">
    </asp:LinqDataSource>
</asp:Content>
