<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    CodeBehind="PortfolioList.aspx.cs" Inherits="web.micajah.backoffice.Pages.PortfolioList"
    Title="Portfolio List" %>

<%@ MasterType VirtualPath="~/MasterPage.master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageBody" runat="server">
    <mits:CommonGridView runat="server" ID="Portfolio_List" DataKeyNames="PortfolioGuid"
        DataSourceID="LinqDataSource_List" Width="600px" ColorScheme="Gray" AutoGenerateColumns="False"
        AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" ShowAddLink="True">
        <Columns>
            <mits:TextBoxField DataField="Active" HeaderText="Active" />
            <mits:TextBoxField DataField="PortfolioOrder" HeaderText="Order" />
            <mits:TextBoxField DataField="AccountName" HeaderText="Account" />
            <mits:TemplateField>
                <ItemTemplate>
                    <asp:HyperLink runat="server" ID="hlDetail" Text='<%# Eval("PortfolioName") %>' NavigateUrl='<%# String.Format("PortfolioEdit.aspx?Portfolio={0}", Eval("PortfolioGuid")) %>' ToolTip="Edit Portfolio" />
                </ItemTemplate>
                <HeaderTemplate>
                    Project
                </HeaderTemplate>
            </mits:TemplateField>
        </Columns>
    </mits:CommonGridView>
    <p>
        *Select portfolio to view its details</p>
    <asp:LinqDataSource ID="LinqDataSource_List" runat="server" ContextTypeName="web.micajah.backoffice.AppCode.BackOfficeDataContext"
        TableName="BackOffice_Portfolios" EnableDelete="true" EnableInsert="false" EnableUpdate="false"
        OnSelecting="LinqDataSource_List_Selecting" OnDeleting="LinqDataSource_List_Deleting">
    </asp:LinqDataSource>
</asp:Content>
